In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [4]:
import numpy as np
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [60]:
# a = np.array([1.0, 3.5])
# # b = np.array([4.5, 1.6])
# r = np.array(n,20)
# r

a = np.arange(400).reshape(20,20)
b = np.arange(400).reshape(20,20)
# b = np.arange(20).reshape(5,5)

# l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20,1)))

0.0

In [16]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [20]:
print(a5.shape == a1.shape)

True


In [21]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [29]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [30]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [32]:
import re 
s = 'ACBCAC'

re.findall('^AC', s)

['AC']

In [37]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [44]:
data = "Office of Research Administration: (734) 647-6333 | 4325 North Quad"
pattern = """
[(]\d{3}[)]\s\d{3}[-]\d{4}

"""
result = re.findall(pattern, data,re.VERBOSE)
result

['(734) 647-6333']

In [48]:


data = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'
pattern = """



(?<=[https]:\/\/)([A-Za-z0-9.]*)

"""
result = re.findall(pattern, data,re.VERBOSE)
result

['google.com', 'www.baidu.com']

In [56]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = """freedom"""
print(len(re.findall(pattern,text)))

6
